sudo: required

env:
  - VERSION=1.4

services:
  - docker

before_install:
  - docker build -t nanobox/memcached:$VERSION ./$VERSION

script: sudo test/run_all.sh $VERSION

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/memcached ./${VERSION};
  - docker tag ${NAMESPACE}/memcached ${NAMESPACE}/memcached:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/memcached:${VERSION}-beta;
  - if [ "$VERSION" == "1.4" ]; then
    docker tag ${NAMESPACE}/memcached ${NAMESPACE}/memcached:beta;
    docker push ${REMOTE}${NAMESPACE}/memcached;
    fi
  - if [ "$BRANCH" == "master" ]; then
    if [ "$VERSION" == "1.4" ]; then
    docker push ${REMOTE}${NAMESPACE}/memcached;
    fi;
    docker tag ${NAMESPACE}/memcached ${NAMESPACE}/memcached:${VERSION};
    docker push ${REMOTE}${NAMESPACE}/memcached:${VERSION};
    else
    docker tag ${NAMESPACE}/memcached ${NAMESPACE}/memcached:${VERSION}-${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/memcached:${VERSION}-${BRANCH//\//_};
    fi
