sudo: required

env:
  - VERSION=1.4
  - VERSION=1.5

services:
  - docker

before_install:
  - sudo apt-get -y install python-pip
  - sudo pip install docker-squash
  - docker build -t nanobox/memcached:$VERSION ./$VERSION

script: sudo test/run_all.sh $VERSION

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - "echo \"Branch: '$BRANCH'; Version: '$VERSION'\";"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/memcached ./${VERSION};
  - docker-squash -t ${NAMESPACE}/memcached:squashed -f nanobox/runit --tmp-dir /var/tmp/squasher ${NAMESPACE}/memcached
  # `$VERSION-beta` tag is always pushed (master or any dev branch)
  - docker tag ${NAMESPACE}/memcached:squashed ${NAMESPACE}/memcached:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/memcached:${VERSION}-beta;
  # `beta` tag is always pushed (master or any dev branch)
  - if [ "$VERSION" == "1.4" ]; then
    docker tag ${NAMESPACE}/memcached:squashed ${NAMESPACE}/memcached:beta;
    docker push ${REMOTE}${NAMESPACE}/memcached:beta;
    fi
  # `latest` tag is only pushed on master && most recent version
  - if [ "$BRANCH" == "master" ] && [ "$VERSION" == "1.4" ]; then
    docker tag ${NAMESPACE}/memcached:squashed ${NAMESPACE}/memcached;
    docker push ${REMOTE}${NAMESPACE}/memcached;
    fi
  # `$VERSION` (latest/stable implied) tag is only pushed on master. tag branch for clarity otherwise (`$VERSION-$BRANCH`)
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/memcached:squashed ${NAMESPACE}/memcached:${VERSION};
    docker push ${REMOTE}${NAMESPACE}/memcached:${VERSION};
    else
    docker tag ${NAMESPACE}/memcached:squashed ${NAMESPACE}/memcached:${VERSION}-${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/memcached:${VERSION}-${BRANCH//\//_};
    fi
